In [ ]:
#Breast Cancer Detection with Logistic Regression

#importing Libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn.datasets

#Getting the DataSet

breast_cancer = sklearn.datasets.load_breast_cancer()

#print(breast_cancer)

X = breast_cancer.data
Y = breast_cancer.target

#print(X)

#print(Y)

#print(X.shape, Y.shape)


data = pd.DataFrame(breast_cancer.data, columns=breast_cancer.feature_names)

data['class'] = breast_cancer.target

data.head()
data.describe()


print(data['class'].value_counts())

print(breast_cancer.target_names)

data.groupby('class').mean()

#Train and Test Split

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X , Y)

print(Y.shape, Y_test.shape, Y_train.shape)

print(X.shape, X_test.shape, Y_train.shape)

X_train, X_test, Y_train, Y_test = train_test_split(X , Y,test_size=0.1)


#print(Y.shape, Y_test.shape, Y_train.shape)

#print(X.shape, X_test.shape, Y_train.shape)


#print(X.mean(), X_test.mean(), X_train.mean())


#print(Y.mean(), Y_test.mean(), Y_train.mean())


X_train, X_test, Y_train, Y_test = train_test_split(X , Y,test_size=0.1, stratify=Y, random_state=1)

print(Y.mean(), Y_test.mean(), Y_train.mean())

print(X_train)

from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression() #loading logistic_regression model to variable classifier

#training the model on training data

classifier.fit(X_train, Y_train)

from sklearn.metrics import accuracy_score

prediction_on_training_data = classifier.predict(X_train)

accuracy_on_training_data = accuracy_score(Y_train, prediction_on_training_data)

print("Accuracy on training data: ", accuracy_on_training_data)

1    357
0    212
Name: class, dtype: int64
['malignant' 'benign']
(569,) (143,) (426,)
(569, 30) (143, 30) (426,)
0.6274165202108963 0.631578947368421 0.626953125
[[1.490e+01 2.253e+01 1.021e+02 ... 2.475e-01 2.866e-01 1.155e-01]
 [1.205e+01 1.463e+01 7.804e+01 ... 6.548e-02 2.747e-01 8.301e-02]
 [1.311e+01 1.556e+01 8.721e+01 ... 1.986e-01 3.147e-01 1.405e-01]
 ...
 [1.258e+01 1.840e+01 7.983e+01 ... 8.772e-03 2.505e-01 6.431e-02]
 [1.349e+01 2.230e+01 8.691e+01 ... 1.282e-01 2.871e-01 6.917e-02]
 [1.919e+01 1.594e+01 1.263e+02 ... 1.777e-01 2.443e-01 6.251e-02]]
Accuracy on training data:  0.951171875


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
print("Accuracy on training data: ", accuracy_on_training_data)


Accuracy on training data:  0.951171875


In [ ]:
prediction_on_test_data = classifier.predict(X_test)

accuracy_on_test_data = accuracy_score(Y_test, prediction_on_test_data)

print("Accuracy on training data: ", accuracy_on_test_data)

Accuracy on training data:  0.9298245614035088


In [ ]:
input_data = (17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189)

input_data_as_array = np.asarray(input_data)

print(input_data)

[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
 1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
 6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
 1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
 4.601e-01 1.189e-01]


In [ ]:
input_data_reshaped = input_data_as_array.reshape(1,-1)

prediction = classifier.predict(input_data_reshaped)

print(prediction)

if (prediction[0]==0):
  print("The Breast Cancer is Malignant")
else:
  print("The Breast Cancer is Beign")  


[0]
The Breast Cancer is Malignant
